### ISSUE TITLE
License type change

### ISSUE THREAD

**Issue by samirsss** [panospet/recursive-deep-hash#2]
Hi,

Thanks for updating the repo with the license. I'd like you to reconsider the license type that was added, since GPLv3 is very restrictive for use by enterprises. I'd prefer if this was apache 2 or Mozilla license.

thanks!

**Comment by panospet** [comment]
Hello, 

License is now updated to MPL2.

**Comment by samirsss** [comment]
Thanks and appreciate the quick turnaround 👍
